name: Build bundles
env:
  PLAYCANVAS_API_KEY: ${{ secrets.PLAYCANVAS_API_KEY }}
  PLAYCANVAS_PROJECT_ID: ${{ secrets.PLAYCANVAS_PROJECT_ID }}

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - name: Upload bundles
        if: ${{ env.PLAYCANVAS_API_KEY != '' && env.PLAYCANVAS_PROJECT_ID != '' }}
        run: npm run push
